language: python
python:
  - "3.3"
  - "3.4.2"
  - "3.4"


# command to install dependencies
install: "pip install -r requirements/dev-requirements.txt"


# command to run tests
script: python manage.py build --coverage

