"""Avatar hashes added

Revision ID: 3e056e90c67
Revises: cd0c89e863
Create Date: 2015-04-11 11:36:09.772333

"""

# revision identifiers, used by Alembic.
revision = '3e056e90c67'
down_revision = 'cd0c89e863'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
