"""Basic user profiles

Revision ID: cd0c89e863
Revises: 5113467d050
Create Date: 2015-04-04 10:42:27.287349

"""

# revision identifiers, used by Alembic.
revision = 'cd0c89e863'
down_revision = '5113467d050'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'last_seen')
    ### end Alembic commands ###
